image: alpine

pages:
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - apk --no-cache add make
  - cd docs
  - make html
  - mv _build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
